config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cards#index'
  resources :cards do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :type

  validates :title, presence: true
  validates :image, presence: true
  validates :type_id, presence: true
  belongs_to :user
  has_many :comments
  
  mount_uploader :image, ImageUploader

  def self.search(search)
    if search != ""
      Card.where('title LIKE(?)', "%#{search}%")
    else
      Card.all
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
  belongs_to :user
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [ 
    {id: 1, name: '自己啓発'}, {id: 2, name: '参考書'}, {id: 3, name: '経済'}, {id: 4, name: '小説'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true, uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }

  has_many :cards
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :move_to_index_destroy, only: [:destroy]

  def index
    @cards = Card.order('created_at DESC').limit(30)
    @cards_p = Card.where(type_id: 1).order('created_at DESC')
    @cards_i = Card.where(type_id: 2).order('created_at DESC')
    @cards_t = Card.where(type_id: 3).order('created_at DESC')
    @cards_g = Card.where(type_id: 4).order('created_at DESC')
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to root_path
    else
      flash.now[:alert] = @card.errors.full_messages
      render :new
    end
  end

  def new
    @card = Card.new
  end

  def show
    @card = Card.find(params[:id])
    @user = User.find(@card.user_id)
    @comment = Comment.new
    @comments = @card.comments.includes(:user)
  end

  def edit
    @card = Card.find(params[:id])
  end
  
  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @card.destroy
       redirect_to root_path
    else
      render :edit
    end
  end

  def search
    @cards = Card.search(params[:keyword])
  end

  private


  def card_params
    params.require(:card).permit(:title, :image, :text, :type_id).merge(user_id: current_user.id)
  end

  def move_to_index_destroy
    @card = Card.find(params[:id])
    redirect_to root_path unless current_user.id == @card.user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to card_path(params[:card_id])  }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, card_id: params[:card_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/cards/_header.html.haml
.header
  .header__top
    = link_to 'Book-Shelf', root_path, class:"title"
    .Search
      =form_with(url: search_cards_path, local: true, method: :get, class: "Form__contents") do |form|
        =form.text_field :keyword,placeholder: "キーワードから探す", class: "Form__inputText"
        %button.Search__btn{type: "submit"}
          = image_tag 'icon/icon-search 1.png', class: 'Search__btn--icon'
    .function

      %ul.function__list
        %li
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
        %li 
          = link_to "新規文書登録", new_card_path, class: 'Button'

app/views/cards/edit.html.haml
.Listing
  .TopIcon
  = form_for @card, method: :put, local: true do |f|
    .Content
      .Content__title
        %label.Content__title__name 文書選択
        = f.file_field :image, class: "Content__AField"
    .Content
      .Content__title
        %label.Content__title__name タイトル
        = f.text_field :title, class: "Content__AField"
    .Content
      .Content__title
        %label.Content__title__name カテゴリー
        = f.collection_select(:type_id, Type.all, :id, :name,{prompt: "選択してください"}, class: "Content__AField" )
    .Content
      .Content__title
        %label.Content__title__name フリーワード
        = f.text_area :text, class: "Content__BField"
    .Send
      = f.submit '登録する', class: 'Send__ABtn'

app/views/cards/index.html.haml
= render 'header'
.main
  .card-display
    %ul.card-display__box
      %li
        %a{href: "#content01"} 新着文書
      %li
        %a{href: "#content02"} 自己啓発
      %li
        %a{href: "#content03"} 参考書
      %li
        %a{href: "#content04"} 経済
      %li
        %a{href: "#content05"} 小説
    .contents
      #content01
        .ProductLists
          - @cards.each do |card|
            .ProductList
              =link_to card_path(card.id), class: 'ProductList__body' do
                .type
                  = card.type.name
                .name
                  = card.title
                .user
                  = icon('fas', 'user')
                  = card.user.name


      #content02
        .ProductLists
          - @cards_p.each do |card|
            .ProductList
              =link_to card_path(card.id), class: 'ProductList__body' do
                .type
                  = card.type.name
                .name
                  = card.title
                .user
                  = icon('fas', 'user')
                  = card.user.name
      #content03
        .ProductLists
          - @cards_i.each do |card|
            .ProductList
              =link_to card_path(card.id), class: 'ProductList__body' do
                .type
                  = card.type.name
                .name
                  = card.title
                .user
                  =icon('fas', 'user')
                  = card.user.name
      #content04
        .ProductLists
          - @cards_t.each do |card|
            .ProductList
              =link_to card_path(card.id), class: 'ProductList__body' do
                .type
                  = card.type.name
                .name
                  = card.title
                .user
                  =icon('fas', 'user')
                  = card.user.name
      #content05
        .ProductLists
          - @cards_g.each do |card|
            .ProductList
              =link_to card_path(card.id), class: 'ProductList__body' do
                .type
                  = card.type.name
                .name
                  = card.title
                .user
                  =icon('fas', 'user')
                  = card.user.name

.footer
  BookーShelf

app/views/cards/new.html.haml
.Listing
  .TopIcon
  = form_for @card do |f|
    .Content
      .Content__title
        %label.Content__title__name 文書選択
        = f.file_field :image, class: "Content__AField"
    .Content
      .Content__title
        %label.Content__title__name タイトル
        = f.text_field :title, class: "Content__AField"
    .Content
      .Content__title
        %label.Content__title__name カテゴリー
        = f.collection_select(:type_id, Type.all, :id, :name,{prompt: "選択してください"}, class: "Content__AField" )
    .Content
      .Content__title
        %label.Content__title__name フリーワード
        = f.text_area :text, class: "Content__BField"
    .Send
      = f.submit '登録する', class: 'Send__ABtn'


  

app/views/cards/search.html.haml
= render 'header'
.main
  %h3.title 
    検索結果
  .content-search
    .ProductLists
      - @cards.each do |card|
        .ProductList
          =link_to card_path(card.id), class: 'ProductList__body' do
            .type
              = card.type.name
            .name
              = card.title
            .user
              =icon('fas', 'user')
              = card.user.name
.footer
  BookーShelf

app/views/cards/show.html.haml
= render 'header'
.show-main
  .main__zoon
    .content
      = image_tag @card.image.url, class: 'Main__image'
      - if user_signed_in? && (current_user.id == @card.user_id)
        .Purchase__content
          .Purchase__form
            = form_with url: card_path(@card), method: :delete , local: true do |f|
              = f.submit '投稿を削除', class: 'Purchase__form__btn', data: { confirm: '【確認】削除すると二度と復活できません。本当に削除しますか？' }
            = form_with url: edit_card_url(@card.id), method: :get, local: true do |f|
              = f.submit '投稿を編集', class: 'Purchase__form__btn'
      .book_box
        .Table
          %table
            %tr
              %th タイトル
              %td
                = @card.title
            %tr
              %th 出品者
              %td
                = @card.user.name
              %tr
                %th レビュー
                %td.long
                  =@card.text
        .Comment__box
          - if user_signed_in?
            = form_with(model: [@card, @comment], class: "New__comment", local: true, id: "new_comment") do |f| 
              = f.text_area :text, class:"New__comment__body", rows: "2"
              = f.submit "コメントする", class:'Comment__btn'
            .Contents
              -if @comments
                - @comments.each do |comment|
                  .CommentText
                    = comment.user.name
                    %p :
                    = comment.text

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookShelf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield